[zen]
src.github = "zen-browser/desktop"
src.use_latest_release = true
fetch.url = "https://github.com/zen-browser/desktop/releases/download/$ver/zen.linux-x86_64.tar.xz"
fetch.tarball = true
#fetch.preferTag = true
