[zen]
src.github = "zen-browser/desktop"
src.filter = "zen\\.linux-specific\\.tar\\.xz"
fetch.preferTag = true

[zen-generic]
src.github = "zen-browser/desktop"
src.filter = "zen\\.linux-generic\\.tar\\.xz"
fetch.preferTag = true
