[zen]
src.github = "zen-browser/desktop"
fetch.url = "https://github.com/zen-browser/desktop/releases/download/$ver/zen.linux-specific.tar.bz2"
fetch.preferTag = true


# Optionally if you want the generic build too, add a second entry
[zen-generic]
src.github = "zen-browser/desktop"
fetch.url = "https://github.com/zen-browser/desktop/releases/download/$ver/zen.linux-generic.tar.bz2"
fetch.preferTag = true